package edu.qit.cloudclass.dao;

import edu.qit.cloudclass.domain.Chapter;
import edu.qit.cloudclass.domain.ChapterSpinner;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Sun Mar 31 10:35:47 CST 2019
     */
    int insert(Chapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Sun Mar 31 10:35:47 CST 2019
     */
    int insertSelective(Chapter record);

    List<Chapter> chapterList(@Param("courseId") String courseId);

    int searchNum(@Param("courseId") String courseId);

    int chapterModify(Chapter chapter);

    int selectChapter(@Param("chapterId") String chapterId);

    int deleteChapter(@Param("chapterId") String chapterId);

    String findChapterAndCourseId(@Param("courseId")String courseId,@Param("chapterId")String chapterId);

    /**
     * 董悦
     */
    String findCourseIdByPrimaryKey(@Param("id") String id);
    List<ChapterSpinner> getChapterList(String courseId);
}