# 设置80端口可能会导致运行失败
#server:
#port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://212.64.23.103:3306/cloudclass?serverTimezone=GMT%2B8
    username: root
    password: 123
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  servlet:
    session:
      cookie:
        http-only: false

mybatis:
  mapper-locations: classpath:/mapper/**.xml