spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.107.102.246:3306/cloudclass?serverTimezone=GMT%2B8
    username: QIT
    password: dy2020@QIT
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  #port: 80
  servlet:
    session:
      cookie:
        http-only: false

mybatis:
  mapper-locations: classpath:/mapper/**.xml