package edu.qit.cloudclass.domain;

import java.util.Date;

public class Chapter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.id
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.course
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.num
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.name
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.video
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.test
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private String test;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.createTime
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chapter.info
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.id
     *
     * @return the value of chapter.id
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.id
     *
     * @param id the value for chapter.id
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.course
     *
     * @return the value of chapter.course
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.course
     *
     * @param course the value for chapter.course
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.num
     *
     * @return the value of chapter.num
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.num
     *
     * @param num the value for chapter.num
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.name
     *
     * @return the value of chapter.name
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.name
     *
     * @param name the value for chapter.name
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.video
     *
     * @return the value of chapter.video
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.video
     *
     * @param video the value for chapter.video
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.test
     *
     * @return the value of chapter.test
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public String getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.test
     *
     * @param test the value for chapter.test
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setTest(String test) {
        this.test = test == null ? null : test.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.createTime
     *
     * @return the value of chapter.createTime
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.createTime
     *
     * @param createtime the value for chapter.createTime
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chapter.info
     *
     * @return the value of chapter.info
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chapter.info
     *
     * @param info the value for chapter.info
     *
     * @mbg.generated Sun Mar 31 17:02:07 CST 2019
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}